(function(){
"use strict";
var PUZZLES=window.RAJA_WEEKLY_PUZZLES||[],MAX_TRIES=4,WEEK_MS=604800000,EPOCH_WEEK_UTC=Date.UTC(2026,6,27);
var STATE_PREFIX="raja_weekly_v2_w",STATS_KEY="raja_weekly_stats_v2",LANG_KEY="familock_lang",THEME_KEY="szpilplac_theme";
var SUPABASE_URL=(window.SZPILPLAC_CONFIG&&window.SZPILPLAC_CONFIG.SUPABASE_URL)||window.SUPABASE_URL||"";
var SUPABASE_ANON_KEY=(window.SZPILPLAC_CONFIG&&window.SZPILPLAC_CONFIG.SUPABASE_ANON_KEY)||window.SUPABASE_ANON_KEY||"";
var T={
pl:{tag:"Tygodniowa śląska zagadka. Ułóż pięć rzeczy we właściwej kolejności.",rule:"Zielona pozycja po sprawdzeniu jest już pewna i zostaje na miejscu. Masz 4 próby.",check:"Sprawdź",tries:"prób",hint:"Pokaż podpowiedź",hintWait:"Podpowiedź po 2 próbach",hintOne:"Podpowiedź po jeszcze 1 próbie",hintText:"{name} powinno być na miejscu {pos}.",win:"Poukładane!",lose:"Nie tym razem",winText:"Dobra robota. Nowa Raja pojawi się w poniedziałek.",loseText:"Poniżej właściwa kolejność. Nowa Raja pojawi się w poniedziałek.",share:"Podziel się wynikiem",copied:"Skopiowano wynik.",week:"Raja",pool:"zestaw {n} z 52",helpTitle:"Jak grać",helpText:"Co tydzień dostajesz pięć elementów. Ułóż je zgodnie z podanym kryterium, używając strzałek. Po sprawdzeniu poprawne miejsca zostają zablokowane. Po dwóch nieudanych próbach możesz odsłonić jedną pozycję. Zestaw zmienia się zawsze w poniedziałek według czasu Europe/Warsaw.",statsTitle:"Statystyki",played:"Rozegrane",wins:"Wygrane",rate:"Skuteczność",best:"Najlepsza seria",before:"Tygodniowa Raja startuje 27 lipca 2026."},
sl:{tag:"Tydniowo śląsko zagodka. Poukładej piyńć rzeczy po dobrym porządku.",rule:"Zielone miyjsce po sprawdzyniu je już pewne i ostowo na placu. Mosz 4 próby.",check:"Wejrzij",tries:"prób",hint:"Pokoż podpowiydź",hintWait:"Podpowiydź po 2 próbach",hintOne:"Podpowiydź po jeszcze 1 próbie",hintText:"{name} mo być na placu {pos}.",win:"Poukładane!",lose:"Niy tym razym",winText:"Dobrze poszło. Nowo Raja bydzie w poniedziałek.",loseText:"Niżyj je dobro kolejność. Nowo Raja bydzie w poniedziałek.",share:"Podziel sie wynikym",copied:"Wynik skopiowany.",week:"Raja",pool:"zestow {n} z 52",helpTitle:"Jak grać",helpText:"Co tydziyń mosz piyńć elymyntów. Poukładej je wedle kryterium strzałkami. Po sprawdzyniu dobre miyjsca ostowajom zawarte. Po dwóch niyudanych próbach możesz pokozać jedno dobre miyjsce. Zestow zmienio sie kożdy poniedziałek wedle czasu Europe/Warsaw.",statsTitle:"Statystyki",played:"Rozegrane",wins:"Wygrane",rate:"Skuteczność",best:"Nojlepszo seryjo",before:"Tydniowo Raja startuje 27 lipca 2026."}
};
function $(id){return document.getElementById(id)}
function getStore(k){try{return localStorage.getItem(k)}catch(e){return null}}
function setStore(k,v){try{localStorage.setItem(k,v)}catch(e){}}
function getJSON(k){try{return JSON.parse(getStore(k)||"null")}catch(e){return null}}
function setJSON(k,v){setStore(k,JSON.stringify(v))}
function esc(s){return String(s).replace(/[&<>\"]/g,function(c){return c==="&"?"&amp;":c==="<"?"&lt;":c===">"?"&gt;":"&quot;"})}
function warsawParts(d){var p=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Warsaw",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d),o={};p.forEach(function(x){if(x.type!=="literal")o[x.type]=Number(x.value)});return o}
function warsawDayUtc(d){var p=warsawParts(d);return Date.UTC(p.year,p.month-1,p.day)}
function weekIndexRaw(){return Math.floor((warsawDayUtc(new Date())-EPOCH_WEEK_UTC)/WEEK_MS)}
function weekDate(idx,day){return new Date(EPOCH_WEEK_UTC+(idx*7+(day||0))*86400000+43200000)}
function fmtDate(d){return new Intl.DateTimeFormat("pl-PL",{day:"numeric",month:"short",timeZone:"Europe/Warsaw"}).format(d).replace(".","")}
function weekRange(i){return fmtDate(weekDate(i,0))+" – "+fmtDate(weekDate(i,6))}
var lang=(getStore(LANG_KEY)==="ŚL"||getStore(LANG_KEY)==="szl")?"sl":"pl",theme=getStore(THEME_KEY)==="dark"?"dark":"light";
var rawWeek=weekIndexRaw(),THIS_WEEK=Math.max(0,rawWeek),STARTED=rawWeek>=0,currentWeek=THIS_WEEK,puzzle=null,order=[],history=[],status="playing",hintData=null;
window.MAX_TRIES=MAX_TRIES;
function stateKey(i){return STATE_PREFIX+i}
function correctOrder(){return puzzle.items.map(function(x){return x.name})}
function valueMap(){var m={};puzzle.items.forEach(function(x){m[x.name]=x.value});return m}
function sameMembers(a,b){return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.slice().sort().join("\u0001")===b.slice().sort().join("\u0001")}
function freshOrder(){var c=correctOrder(),ps=[[1,0,3,4,2],[1,2,0,4,3],[1,3,4,0,2],[1,4,3,0,2],[2,0,4,1,3],[2,3,0,4,1],[3,0,4,2,1],[4,2,0,1,3]],p=ps[(currentWeek+puzzle.id)%ps.length];return p.map(function(i){return c[i]})}
function sanitize(s){var c=correctOrder();if(!s||!sameMembers(s.order,c))return null;var h=Array.isArray(s.history)?s.history.filter(function(x){return Array.isArray(x)&&x.length===5}).slice(0,MAX_TRIES):[],st=(s.status==="won"||s.status==="lost")?s.status:"playing";if(st==="playing"&&h.length>=MAX_TRIES)return null;var hd=s.hintData&&s.hintData.name?{name:s.hintData.name,pos:Number(s.hintData.pos)}:null;return{order:s.order.slice(),history:h,status:st,hintData:hd}}
function sync(){window.currentDay=currentWeek;window.TODAY_IDX=THIS_WEEK;window.guessHistory=history;window.status=status;window.hintData=hintData}
function persist(){setJSON(stateKey(currentWeek),{order:order,history:history,status:status,hintData:hintData});sync()}
function lastMask(){return history.length?history[history.length-1]:null}
function fixedAt(i){var m=lastMask();return !!(m&&m[i])}
function target(i,dir){var j=i+dir;while(j>=0&&j<order.length){if(!fixedAt(j))return j;j+=dir}return-1}
function move(i,dir){if(status!=="playing"||fixedAt(i))return;var j=target(i,dir);if(j<0)return;var t=order[i];order[i]=order[j];order[j]=t;persist();renderList()}
function loadWeek(i){if(!STARTED){$("notice").hidden=false;$("notice").textContent=T[lang].before;$("banner").hidden=true;$("hintBar").hidden=true;$("list").innerHTML="";$("attempts").innerHTML="";$("checkBtn").hidden=true;updateWeekNav();return}currentWeek=Math.max(0,Math.min(THIS_WEEK,Math.floor(Number(i)||0)));puzzle=PUZZLES[currentWeek%PUZZLES.length];if(!puzzle){$("notice").hidden=false;$("notice").textContent="Brak zestawu Rai.";return}var s=sanitize(getJSON(stateKey(currentWeek)));if(s){order=s.order;history=s.history;status=s.status;hintData=s.hintData}else{order=freshOrder();history=[];status="playing";hintData=null;persist()}$("notice").hidden=true;$("banner").hidden=false;$("result").classList.remove("show");renderAll();if(status!=="playing")showResult(status==="won")}
function updateWeekNav(){$("prevWeek").disabled=!STARTED||currentWeek<=0;$("nextWeek").disabled=!STARTED||currentWeek>=THIS_WEEK;var n=PUZZLES.length?(currentWeek%PUZZLES.length)+1:0;$("weekLabel").innerHTML=esc(T[lang].week+" #"+(currentWeek+1))+"<small>"+esc(weekRange(currentWeek))+" · "+esc(T[lang].pool.replace("{n}",n))+"</small>"}
function renderHeader(){if(!puzzle)return;$("tagline").textContent=T[lang].tag;$("category").textContent=puzzle.category;$("criterion").textContent=puzzle.criterion;$("rule").textContent=T[lang].rule;$("checkBtn").textContent=T[lang].check;$("shareBtn").textContent=T[lang].share;$("langPl").classList.toggle("on",lang==="pl");$("langSl").classList.toggle("on",lang==="sl")}
function renderList(){var el=$("list");el.innerHTML="";var mask=lastMask();order.forEach(function(name,i){var li=document.createElement("li"),controls="";li.className="row"+(mask&&mask[i]?" fixed":"");if(status==="playing"&&!fixedAt(i)){controls='<div class="arrows"><button type="button" data-move="-1" data-i="'+i+'" '+(target(i,-1)<0?"disabled":"")+'>↑</button><button type="button" data-move="1" data-i="'+i+'" '+(target(i,1)<0?"disabled":"")+'>↓</button></div>'}else if(mask&&mask[i])controls='<div class="tick">✓</div>';li.innerHTML='<div class="rank">'+(i+1)+'</div><div class="name">'+esc(name)+'</div>'+controls;el.appendChild(li)});Array.prototype.forEach.call(el.querySelectorAll("[data-move]"),function(b){b.addEventListener("click",function(){move(Number(b.dataset.i),Number(b.dataset.move))})})}
function renderAttempts(){var el=$("attempts");el.innerHTML="";if(status!=="playing"){el.style.display="none";return}el.style.display="flex";for(var i=0;i<MAX_TRIES;i++){var d=document.createElement("span");d.className="dot"+(i<history.length?" used":"");el.appendChild(d)}var l=document.createElement("span");l.className="attempt-label";l.textContent=(MAX_TRIES-history.length)+" "+T[lang].tries;el.appendChild(l)}
function renderHint(){var b=$("hintBtn"),m=$("hintMsg");if(status!=="playing"){$("hintBar").hidden=true;return}$("hintBar").hidden=false;if(hintData){b.hidden=true;m.hidden=false;m.textContent=T[lang].hintText.replace("{name}",hintData.name).replace("{pos}",hintData.pos);return}m.hidden=true;b.hidden=false;b.disabled=history.length<2;b.textContent=history.length>=2?T[lang].hint:(history.length===1?T[lang].hintOne:T[lang].hintWait)}
function renderAll(){renderHeader();updateWeekNav();renderList();renderAttempts();renderHint();$("checkBtn").hidden=status!=="playing";$("checkBtn").disabled=false;sync()}
function useHint(){if(status!=="playing"||hintData||history.length<2)return;var c=correctOrder();for(var i=0;i<c.length;i++){if(order[i]!==c[i]){hintData={name:c[i],pos:i+1};break}}if(!hintData)hintData={name:c[0],pos:1};persist();renderHint()}
function check(){if(status!=="playing")return;var c=correctOrder(),mask=order.map(function(name,i){return name===c[i]});history.push(mask);if(mask.every(Boolean)){status="won";persist();finish(true);return}if(history.length>=MAX_TRIES){status="lost";persist();finish(false);return}persist();renderAll()}
function finish(won){renderAll();showResult(won);recordStats(won);trackEvent(won);saveAccount(won)}
function showResult(won){$("result").classList.add("show");$("resultTitle").textContent=won?T[lang].win:T[lang].lose;$("resultText").textContent=won?T[lang].winText:T[lang].loseText;var vals=valueMap(),c=correctOrder(),ul=$("resultList");ul.innerHTML="";c.forEach(function(name,i){var li=document.createElement("li");li.className="row";li.innerHTML='<div class="rank">'+(i+1)+'</div><div class="name">'+esc(name)+'</div><div class="value">'+esc(vals[name])+'</div>';ul.appendChild(li)})}
function statsData(){var s=getJSON(STATS_KEY);return s&&s.weeks?s:{weeks:{}}}
function recordStats(won){var s=statsData(),k=String(currentWeek);if(!s.weeks[k]){s.weeks[k]={won:!!won,tries:history.length,hint:!!hintData,at:new Date().toISOString()};setJSON(STATS_KEY,s)}}
function calcStats(){var s=statsData(),keys=Object.keys(s.weeks).map(Number).filter(function(n){return Number.isFinite(n)}).sort(function(a,b){return a-b}),wins=0,best=0,run=0,last=null;keys.forEach(function(k){var r=s.weeks[String(k)];if(r&&r.won){wins++;run=(last!==null&&k===last+1)?run+1:1;best=Math.max(best,run)}else run=0;last=k});return{played:keys.length,wins:wins,rate:keys.length?Math.round(wins/keys.length*100)+"%":"–",best:best}}
function renderStats(){var s=calcStats(),l=T[lang],d=[[s.played,l.played],[s.wins,l.wins],[s.rate,l.rate],[s.best,l.best]];$("statsBody").innerHTML=d.map(function(x){return'<div class="stat"><strong>'+esc(x[0])+'</strong><span>'+esc(x[1])+'</span></div>'}).join("");$("statsTitle").textContent=l.statsTitle}
function score(won){if(!won)return 5;var a=[150,120,90,60],v=a[Math.max(0,Math.min(3,history.length-1))];return hintData?Math.max(20,v-25):v}
function payload(won){return{game:"zorta",mode:"weekly",puzzleNo:currentWeek+1,puzzle_no:currentWeek+1,dayIndex:currentWeek,won:!!won,tries:history.length,errors:Math.max(0,history.length-(won?1:0)),score:score(won),maxAttempts:MAX_TRIES,isCurrent:currentWeek===THIS_WEEK,hintUsed:!!hintData,finishedAt:new Date().toISOString(),source:"raja-weekly-v2"}}
function saveAccount(won){if(currentWeek!==THIS_WEEK||!window.SZP_GAME_SAVE||typeof window.SZP_GAME_SAVE.saveResult!=="function")return;window.SZP_GAME_SAVE.saveResult(payload(won),{skipMessage:"Do rankingu zapisuje się tylko bieżąca Raja.",noAccountMessage:"Grasz bez konta. Wynik Rai został zapisany lokalnie.",savedMessage:"Wynik Rai zapisany na koncie.",errorMessage:"Nie udało się zapisać wyniku Rai."}).catch(function(e){console.warn("Raja account save",e)})}
function trackEvent(won){if(!SUPABASE_URL||!SUPABASE_ANON_KEY)return;var p={game:"zorta",puzzle_no:currentWeek+1,puzzle_word:puzzle.category,won:!!won,tries:history.length,lang:lang,mode:"weekly"};fetch(SUPABASE_URL+"/rest/v1/szpilplac_events",{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_ANON_KEY,"Authorization":"Bearer "+SUPABASE_ANON_KEY,"Prefer":"return=minimal"},body:JSON.stringify(p)}).catch(function(){})}
function buildShare(){var sc=(status==="won"?history.length:"X")+"/"+MAX_TRIES,grid=history.map(function(m){return m.map(function(v){return v?"🟩":"⬜"}).join("")}).join("\n");return"Raja #"+(currentWeek+1)+"\n"+sc+"\n\n"+grid+"\n\nhttps://szpilplac.familock.pl/raja/"}
function share(){var txt=buildShare(),p=(navigator.clipboard&&window.isSecureContext)?navigator.clipboard.writeText(txt):Promise.reject();p.then(function(){var old=$("shareBtn").textContent;$("shareBtn").textContent=T[lang].copied;setTimeout(function(){$("shareBtn").textContent=old},1400)}).catch(function(){window.prompt("Skopiuj wynik:",txt)})}
function setLang(l){lang=l;setStore(LANG_KEY,l==="sl"?"ŚL":"PL");if(puzzle){renderAll();if(status!=="playing")showResult(status==="won")}renderStats()}
function setTheme(t){theme=t;document.documentElement.setAttribute("data-theme",theme);setStore(THEME_KEY,theme)}
function openModal(id){$(id).classList.add("show")}
function closeModal(id){$(id).classList.remove("show")}
document.documentElement.setAttribute("data-theme",theme);
$("prevWeek").addEventListener("click",function(){if(currentWeek>0)loadWeek(currentWeek-1)});$("nextWeek").addEventListener("click",function(){if(currentWeek<THIS_WEEK)loadWeek(currentWeek+1)});$("checkBtn").addEventListener("click",check);$("hintBtn").addEventListener("click",useHint);$("shareBtn").addEventListener("click",share);$("langPl").addEventListener("click",function(){setLang("pl")});$("langSl").addEventListener("click",function(){setLang("sl")});$("themeBtn").addEventListener("click",function(){setTheme(theme==="dark"?"light":"dark")});$("helpBtn").addEventListener("click",function(){$("helpTitle").textContent=T[lang].helpTitle;$("helpText").textContent=T[lang].helpText;openModal("helpModal")});$("statsBtn").addEventListener("click",function(){renderStats();openModal("statsModal")});Array.prototype.forEach.call(document.querySelectorAll("[data-close]"),function(b){b.addEventListener("click",function(){closeModal(b.dataset.close)})});Array.prototype.forEach.call(document.querySelectorAll(".modal-bg"),function(bg){bg.addEventListener("click",function(e){if(e.target===bg)bg.classList.remove("show")})});
if(!Array.isArray(PUZZLES)||PUZZLES.length!==52){$("notice").hidden=false;$("notice").textContent="Błąd danych Rai: potrzebne są dokładnie 52 zestawy.";$("banner").hidden=true;$("checkBtn").hidden=true;$("hintBar").hidden=true}else loadWeek(THIS_WEEK);
})();
