
/* Szpilplac Kamraty z placu v2 */
(function(){
"use strict";
var VERSION="v2",AUTH_STORAGE_KEY="szpilplac-auth-v05",sb=null,currentUser=null,publicMap={},followedMap={},reactionMemory={};
var REACTIONS=[
  {key:"Fest!",icon:"✦"},
  {key:"Przaja Ci!",icon:"♡"},
  {key:"Dobro robota!",icon:"✓"},
  {key:"Gonia Cie!",icon:"→"},
  {key:"Gowa paruje!",icon:"≋"}
];
function esc(x){return String(x==null?"":x).replace(/[&<>"']/g,function(ch){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]||ch;});}
function fmt(n){return String(Number(n||0));}
function fmtDate(x){if(!x)return "—";try{return new Date(x).toLocaleString("pl-PL");}catch(e){return "—";}}
function reactionMeta(key){for(var i=0;i<REACTIONS.length;i++){if(REACTIONS[i].key===key)return REACTIONS[i];}return {key:key,icon:"•"};}
function reactionHtml(key){var r=reactionMeta(key);return '<span class="react-icon" aria-hidden="true">'+esc(r.icon)+'</span><span>'+esc(r.key)+'</span>';}
function cfg(){return {url:window.SUPABASE_URL||(window.SZPILPLAC_CONFIG&&window.SZPILPLAC_CONFIG.SUPABASE_URL)||"",key:window.SUPABASE_ANON_KEY||(window.SZPILPLAC_CONFIG&&window.SZPILPLAC_CONFIG.SUPABASE_ANON_KEY)||""};}
function initClient(){if(sb)return true;var c=cfg();if(!c.url||!c.key||!window.supabase)return false;if(window.__SZPILPLAC_SUPABASE_CLIENT)sb=window.__SZPILPLAC_SUPABASE_CLIENT;else{sb=window.supabase.createClient(c.url,c.key,{auth:{storageKey:AUTH_STORAGE_KEY,detectSessionInUrl:false,persistSession:true,autoRefreshToken:true}});window.__SZPILPLAC_SUPABASE_CLIENT=sb;}return true;}
async function session(){if(!initClient())return null;try{var r=await sb.auth.getSession();if(r&&r.data&&r.data.session){currentUser=r.data.session.user||null;return r.data.session;}}catch(e){}try{var raw=localStorage.getItem(AUTH_STORAGE_KEY);if(!raw)return null;var data=JSON.parse(raw),s=data.currentSession||data.session||data;if(s&&s.access_token&&s.refresh_token){try{var set=await sb.auth.setSession({access_token:s.access_token,refresh_token:s.refresh_token});if(set&&set.data&&set.data.session){currentUser=set.data.session.user||null;return set.data.session;}}catch(e){}currentUser=s.user||null;return s;}}catch(e){}return null;}
async function rpc(name,args){if(!initClient())throw new Error("Brak połączenia z Supabase.");var r=await sb.rpc(name,args||{});if(r.error)throw r.error;return r.data;}
function toast(text,type){var el=document.getElementById("kamratToast");if(!el){el=document.createElement("div");el.id="kamratToast";el.className="kamrat-toast";document.body.appendChild(el);}el.textContent=text||"";el.className="kamrat-toast show "+(type||"ok");clearTimeout(el.__timer);el.__timer=setTimeout(function(){el.classList.remove("show");},2600);}
function injectStyle(){if(document.getElementById("kamratyStyle"))return;var s=document.createElement("style");s.id="kamratyStyle";s.textContent=`
.kamraty-panel{margin:18px 0;padding:16px;border:1px solid var(--line,#c9bfa6);border-radius:18px;background:linear-gradient(180deg,rgba(191,138,58,.08),rgba(191,138,58,.025))}
.kamraty-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:12px}.kamraty-title{margin:0;font-family:Oswald,system-ui,sans-serif;font-size:21px;line-height:1.05;text-transform:uppercase;letter-spacing:.04em}.kamraty-sub{margin:5px 0 0;color:var(--ink2,#6a6150);font-size:12.5px;line-height:1.45}
.kamraty-toggle{display:flex;align-items:center;gap:8px;min-height:40px;padding:9px 12px;border:1px solid var(--line,#c9bfa6);border-radius:999px;background:var(--surface,#fbf7ee);font-size:12px;font-weight:900;color:var(--ink,#23201a)}.kamraty-toggle input{accent-color:var(--green,#2f4a39)}
.kamraty-grid{display:grid;gap:10px}.kamrat-card{padding:13px;border:1px solid var(--line,#c9bfa6);border-radius:15px;background:var(--surface,#fbf7ee)}.kamrat-top{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.kamrat-name{font-family:Oswald,system-ui,sans-serif;font-size:20px;text-transform:uppercase;line-height:1.05}.kamrat-meta{margin-top:4px;color:var(--ink2,#6a6150);font-size:12px;line-height:1.45}
.kamrat-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin:10px 0}.kamrat-stat{padding:8px;border:1px solid var(--line,#c9bfa6);border-radius:12px;background:var(--surface2,#f3ecda)}.kamrat-stat small{display:block;color:var(--ink2,#6a6150);font-size:9.5px;font-weight:900;text-transform:uppercase;letter-spacing:.05em}.kamrat-stat strong{display:block;margin-top:3px;font-family:Oswald,system-ui,sans-serif;font-size:20px;line-height:1}
.kamrat-actions,.reaction-row,.rank-kamrat-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.kamrat-btn,.reaction-chip,.rank-kamrat-btn{min-height:34px;display:inline-flex;align-items:center;justify-content:center;gap:6px;padding:7px 10px;border:1px solid var(--line,#c9bfa6);border-radius:999px;background:var(--surface2,#f3ecda);color:var(--ink,#23201a);font-size:11.5px;font-weight:900;text-decoration:none;transition:transform .12s,background .12s,border-color .12s,color .12s}.kamrat-btn:hover,.reaction-chip:hover,.rank-kamrat-btn:hover{background:var(--surface,#fbf7ee);color:var(--green,#2f4a39);transform:translateY(-1px)}.kamrat-btn.gold,.rank-kamrat-btn.gold{border-color:var(--gold,#bf8a3a);background:rgba(191,138,58,.14)}.kamrat-btn.danger{color:var(--danger,#b5482f)}
.reaction-chip{font-size:11px;color:var(--green,#2f4a39)}.reaction-chip .react-icon{width:1.15em;display:inline-flex;justify-content:center;color:var(--gold,#bf8a3a);font-weight:900}.reaction-chip.active{background:var(--green,#2f4a39);border-color:var(--green,#2f4a39);color:#fff}.reaction-chip.active .react-icon{color:#fff}.reaction-counts,.reaction-status{margin-top:7px;color:var(--ink2,#6a6150);font-size:11.5px;line-height:1.45}
.compare-box{display:none;margin-top:10px;padding:10px;border:1px dashed rgba(191,138,58,.6);border-radius:13px;background:rgba(191,138,58,.08)}.compare-box.show{display:block}.compare-row{display:grid;grid-template-columns:1fr auto auto;gap:8px;padding:6px 0;border-bottom:1px solid var(--line,#c9bfa6);font-size:12px}.compare-row:last-child{border-bottom:0}.compare-row strong{color:var(--ink,#23201a)}.compare-row span{color:var(--ink2,#6a6150);font-weight:800}
.kamrat-empty{padding:12px;border:1px dashed var(--line,#c9bfa6);border-radius:13px;color:var(--ink2,#6a6150);font-size:13px;line-height:1.5;background:rgba(255,255,255,.03)}.rank-kamrat-actions{grid-column:3/5}.rank-kamrat-btn.is-followed{border-color:rgba(47,74,57,.55);background:rgba(47,74,57,.10)}
.kamrat-toast{position:fixed;left:50%;bottom:18px;z-index:9999;max-width:min(520px,calc(100vw - 28px));transform:translate(-50%,16px);opacity:0;pointer-events:none;padding:11px 14px;border:1px solid var(--line,#c9bfa6);border-radius:999px;background:rgba(38,32,24,.96);color:#ede5d0;box-shadow:0 18px 55px -30px rgba(0,0,0,.75);font-size:12.5px;font-weight:900;text-align:center;transition:opacity .16s,transform .16s}.kamrat-toast.show{opacity:1;transform:translate(-50%,0)}.kamrat-toast.err{border-color:var(--danger,#b5482f)}
@media(max-width:720px){.kamraty-head{display:grid}.kamrat-stats{grid-template-columns:1fr 1fr}.rank-kamrat-actions{grid-column:2/5}}@media(max-width:430px){.kamrat-stats{grid-template-columns:1fr}.kamrat-actions,.reaction-row{display:grid}.kamrat-btn,.reaction-chip{width:100%}.kamrat-toast{border-radius:16px}}
`;document.head.appendChild(s);}
function reactionCountsHtml(obj){obj=obj||{};var items=REACTIONS.map(function(r){var n=Number(obj[r.key]||0);return n?esc(r.icon+" "+r.key)+" × "+n:"";}).filter(Boolean);return items.length?"Dzisiaj: "+items.join(" · "):"Dzisiaj bez reakcji.";}
async function loadPublicMap(){try{var rows=await rpc("szp_public_players",{});publicMap={};(rows||[]).forEach(function(r){if(r&&r.user_id)publicMap[String(r.user_id)]=r;});}catch(e){publicMap={};}return publicMap;}
async function loadFollowedMap(){followedMap={};if(!currentUser)return followedMap;try{var rows=await rpc("szp_my_kamraty",{});(rows||[]).forEach(function(r){if(r&&r.user_id)followedMap[String(r.user_id)]=r;});}catch(e){}return followedMap;}
function updateReactionUi(id,reaction){reactionMemory[id]=reaction;Array.prototype.slice.call(document.querySelectorAll('[data-kamrat-react="'+CSS.escape(id)+'"]')).forEach(function(btn){btn.classList.toggle("active",btn.getAttribute("data-reaction")===reaction);});Array.prototype.slice.call(document.querySelectorAll('[data-reaction-status="'+CSS.escape(id)+'"]')).forEach(function(el){el.textContent="Reakcja zapisana: "+reactionMeta(reaction).icon+" "+reaction;});}
async function follow(id){await session();if(!currentUser){toast("Najpierw zaloguj się na konto.","err");location.href="konto.html?login=1";return;}await rpc("szp_follow_player",{p_target_id:id});toast("Dodano do Kamratów z placu.");await refreshAll();}
async function unfollow(id){await rpc("szp_unfollow_player",{p_target_id:id});toast("Usunięto z Kamratów z placu.");await refreshAll();}
async function sendReaction(id,reaction){await rpc("szp_send_reaction",{p_target_id:id,p_reaction:reaction});updateReactionUi(id,reaction);toast("Reakcja zapisana: "+reactionMeta(reaction).icon+" "+reaction);if(location.pathname.indexOf("konto")!==-1)setTimeout(renderKontoKamraty,450);}
function reactionButtons(id,myReaction){myReaction=reactionMemory[id]||myReaction||"";return '<div class="reaction-row">'+REACTIONS.map(function(r){return '<button type="button" class="reaction-chip '+(myReaction===r.key?"active":"")+'" data-kamrat-react="'+esc(id)+'" data-reaction="'+esc(r.key)+'">'+reactionHtml(r.key)+'</button>';}).join("")+'</div><div class="reaction-status" data-reaction-status="'+esc(id)+'">'+(myReaction?"Twoja reakcja: "+esc(reactionMeta(myReaction).icon+" "+myReaction):"Wybierz jedną reakcję dziennie.")+'</div>';}
async function compare(id,box){if(!box)return;box.classList.toggle("show");if(!box.classList.contains("show"))return;box.innerHTML="Porównuję...";try{var rows=await rpc("szp_compare_with_player",{p_target_id:id});box.innerHTML=(rows||[]).map(function(r){return '<div class="compare-row"><strong>'+esc(r.metric)+'</strong><span>Ty: '+esc(r.me_value)+'</span><span>Kamrat: '+esc(r.target_value)+'</span></div>';}).join("")||"Brak danych do porównania.";}catch(e){box.innerHTML="Nie udało się porównać: "+esc(e.message||e);}}
async function renderKontoKamraty(){var panel=document.getElementById("kamratyPanel");if(!panel)return;await session();if(!currentUser){panel.innerHTML='<div class="kamrat-empty">Zaloguj się, żeby korzystać z Kamratów z placu.</div>';return;}var state=false;try{var st=await rpc("szp_my_public_profile",{});state=!!(Array.isArray(st)?st[0]&&st[0].public_profile:st&&st.public_profile);}catch(e){}var friends=[];try{friends=await rpc("szp_my_kamraty",{});}catch(e){friends=[];}
panel.innerHTML='<div class="kamraty-head"><div><h2 class="kamraty-title">Kamraty z placu</h2><p class="kamraty-sub">Publiczny profil, obserwowani gracze, porównanie wyników i małe reakcje bez komentarzy.</p></div><label class="kamraty-toggle"><input type="checkbox" id="publicProfileToggle" '+(state?"checked":"")+'> Profil publiczny</label></div><div id="kamratyList" class="kamraty-grid"></div>';
var list=document.getElementById("kamratyList");if(!friends.length){list.innerHTML='<div class="kamrat-empty">Nie masz jeszcze kamratów. Wejdź w ranking i dodaj graczy z publicznym profilem.</div>';}else{list.innerHTML=friends.map(function(f){var my=reactionMemory[f.user_id]||f.my_reaction_today||"";return '<article class="kamrat-card" data-kamrat-id="'+esc(f.user_id)+'"><div class="kamrat-top"><div><div class="kamrat-name">'+esc(f.login||"gracz")+'</div><div class="kamrat-meta">Ranga: '+esc(f.rank_name||"Gorol")+' · ostatnio: '+esc(fmtDate(f.last_play))+'</div></div><a class="kamrat-btn" href="gracz.html?u='+encodeURIComponent(f.user_id)+'">Profil</a></div><div class="kamrat-stats"><div class="kamrat-stat"><small>Punkty</small><strong>'+fmt(f.points)+'</strong></div><div class="kamrat-stat"><small>Gry</small><strong>'+fmt(f.games_played)+'</strong></div><div class="kamrat-stat"><small>Wygrane</small><strong>'+fmt(f.wins)+'</strong></div><div class="kamrat-stat"><small>Dzisiaj</small><strong>'+fmt(f.played_today)+'</strong></div></div><div class="kamrat-actions"><button type="button" class="kamrat-btn gold" data-kamrat-compare="'+esc(f.user_id)+'">Porównaj</button><button type="button" class="kamrat-btn danger" data-kamrat-remove="'+esc(f.user_id)+'">Usuń</button></div><div class="reaction-counts">'+esc(reactionCountsHtml(f.reaction_counts||{}))+'</div>'+reactionButtons(f.user_id,my)+'<div class="compare-box" id="compare-'+esc(f.user_id)+'"></div></article>';}).join("");}
var toggle=document.getElementById("publicProfileToggle");if(toggle){toggle.addEventListener("change",async function(){toggle.disabled=true;try{await rpc("szp_set_public_profile",{p_public:!!toggle.checked});toast(toggle.checked?"Profil publiczny włączony.":"Profil publiczny wyłączony.");}catch(e){toggle.checked=!toggle.checked;toast("Nie udało się zmienić profilu publicznego: "+(e.message||e),"err");}finally{toggle.disabled=false;}});}}
function ensureKontoPanel(){var profile=document.getElementById("profileCard");if(!profile||document.getElementById("kamratyPanel"))return;var progress=document.getElementById("profileProgress");var panel=document.createElement("section");panel.id="kamratyPanel";panel.className="kamraty-panel";panel.innerHTML='<div class="kamrat-empty">Ładuję Kamratów z placu...</div>';if(progress&&progress.parentNode)progress.parentNode.insertBefore(panel,progress.nextSibling);else profile.appendChild(panel);renderKontoKamraty();}
function buildRankingActions(row,id){var pub=publicMap[id];if(!pub)return;var isMe=currentUser&&currentUser.id===id,isFollowed=!!followedMap[id];var box=document.createElement("div");box.className="rank-kamrat-actions";var html='<a class="rank-kamrat-btn" href="gracz.html?u='+encodeURIComponent(id)+'">Profil publiczny</a>';if(!isMe){html+=isFollowed?'<button type="button" class="rank-kamrat-btn is-followed" data-rank-unfollow="'+esc(id)+'">W kamratach</button>':'<button type="button" class="rank-kamrat-btn gold" data-rank-follow="'+esc(id)+'">Dodaj do kamratów</button>';}box.innerHTML=html;var details=row.querySelector(".details")||row;details.parentNode.insertBefore(box,details.nextSibling);}
async function enhanceRankingRows(){if(location.pathname.indexOf("ranking")===-1)return;await session();await loadPublicMap();await loadFollowedMap();Array.prototype.slice.call(document.querySelectorAll(".rank-row[data-user-id]")).forEach(function(row){Array.prototype.slice.call(row.querySelectorAll(".rank-kamrat-actions")).forEach(function(x){x.remove();});var id=row.getAttribute("data-user-id");if(id)buildRankingActions(row,id);});}
async function refreshAll(){await loadPublicMap();await loadFollowedMap();enhanceRankingRows();renderKontoKamraty();if(location.pathname.indexOf("gracz")!==-1)renderPublicProfilePage();}
async function renderPublicProfilePage(){var box=document.getElementById("publicProfileBox");if(!box)return;await session();var id=new URLSearchParams(location.search).get("u")||"";if(!id){box.innerHTML='<div class="kamrat-empty">Brak wskazanego gracza.</div>';return;}box.innerHTML='<div class="kamrat-empty">Ładuję profil...</div>';try{var rows=await rpc("szp_get_public_player",{p_player_id:id}),p=Array.isArray(rows)?rows[0]:rows;if(!p){box.innerHTML='<div class="kamrat-empty">Ten profil nie jest publiczny albo nie istnieje.</div>';return;}await loadFollowedMap();var f=followedMap[id]||{},isMe=currentUser&&currentUser.id===id,isFollowed=!!followedMap[id],my=reactionMemory[id]||f.my_reaction_today||"";box.innerHTML='<section class="kamraty-panel"><div class="kamraty-head"><div><h1 class="kamraty-title">'+esc(p.login||"Gracz")+'</h1><p class="kamraty-sub">Publiczny profil gracza Szpilplaca. Bez maila, bez prywatnych danych i bez spoilerów.</p></div></div><div class="kamrat-stats"><div class="kamrat-stat"><small>Ranga</small><strong>'+esc(p.rank_name||"Gorol")+'</strong></div><div class="kamrat-stat"><small>Punkty</small><strong>'+fmt(p.points)+'</strong></div><div class="kamrat-stat"><small>Gry</small><strong>'+fmt(p.games_played)+'</strong></div><div class="kamrat-stat"><small>Wygrane</small><strong>'+fmt(p.wins)+'</strong></div></div><div class="kamrat-stats"><div class="kamrat-stat"><small>Dziś</small><strong>'+fmt(p.played_today)+'</strong></div><div class="kamrat-stat"><small>7 dni</small><strong>'+fmt(p.played_7d)+'</strong></div><div class="kamrat-stat"><small>Skuteczność</small><strong>'+fmt(p.win_pct)+'%</strong></div><div class="kamrat-stat"><small>Ostatnio</small><strong style="font-size:14px">'+esc(fmtDate(p.last_play))+'</strong></div></div><div class="kamrat-actions"><a class="kamrat-btn" href="ranking.html">Ranking</a><a class="kamrat-btn" href="konto.html">Moje konto</a>'+(!isMe&&currentUser?(isFollowed?'<button type="button" class="kamrat-btn" data-rank-unfollow="'+esc(id)+'">W kamratach</button>':'<button type="button" class="kamrat-btn gold" data-rank-follow="'+esc(id)+'">Dodaj do kamratów</button>'):"")+(!isMe&&currentUser?'<button type="button" class="kamrat-btn gold" data-kamrat-compare="'+esc(id)+'">Porównaj</button>':"")+'</div>'+(!isMe&&currentUser?reactionButtons(id,my):'<div class="kamrat-empty">Zaloguj się, żeby dać reakcję albo dodać gracza do kamratów.</div>')+'<div class="compare-box" id="compare-'+esc(id)+'"></div></section>';if(my)updateReactionUi(id,my);}catch(e){box.innerHTML='<div class="kamrat-empty">Nie udało się pobrać profilu: '+esc(e.message||e)+'</div>';}}
document.addEventListener("click",function(e){var btn=e.target&&e.target.closest?e.target.closest("[data-rank-follow],[data-rank-unfollow],[data-kamrat-remove],[data-kamrat-compare],[data-kamrat-react]"):null;if(!btn)return;var id;if(btn.hasAttribute("data-rank-follow")){id=btn.getAttribute("data-rank-follow");btn.disabled=true;follow(id).catch(function(err){toast(err.message||String(err),"err");}).finally(function(){btn.disabled=false;});}else if(btn.hasAttribute("data-rank-unfollow")){id=btn.getAttribute("data-rank-unfollow");btn.disabled=true;unfollow(id).catch(function(err){toast(err.message||String(err),"err");}).finally(function(){btn.disabled=false;});}else if(btn.hasAttribute("data-kamrat-remove")){id=btn.getAttribute("data-kamrat-remove");btn.disabled=true;unfollow(id).catch(function(err){toast(err.message||String(err),"err");}).finally(function(){btn.disabled=false;});}else if(btn.hasAttribute("data-kamrat-compare")){id=btn.getAttribute("data-kamrat-compare");compare(id,document.getElementById("compare-"+id)||(btn.closest(".kamrat-card")&&btn.closest(".kamrat-card").querySelector(".compare-box")));}else if(btn.hasAttribute("data-kamrat-react")){id=btn.getAttribute("data-kamrat-react");var reaction=btn.getAttribute("data-reaction");btn.disabled=true;sendReaction(id,reaction).catch(function(err){toast(err.message||String(err),"err");}).finally(function(){btn.disabled=false;});}});
function boot(){injectStyle();initClient();if(location.pathname.indexOf("konto")!==-1){var timer=setInterval(function(){var p=document.getElementById("profileCard");if(p&&!p.classList.contains("hidden"))ensureKontoPanel();},800);setTimeout(function(){clearInterval(timer);},30000);new MutationObserver(function(){ensureKontoPanel();}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["class"]});}
if(location.pathname.indexOf("ranking")!==-1){setTimeout(enhanceRankingRows,600);setTimeout(enhanceRankingRows,1600);new MutationObserver(function(){clearTimeout(window.__kamratRankTimer);window.__kamratRankTimer=setTimeout(enhanceRankingRows,120);}).observe(document.body,{childList:true,subtree:true});}
if(location.pathname.indexOf("gracz")!==-1){renderPublicProfilePage();}}
window.SZP_KAMRATY={version:VERSION,refresh:refreshAll};console.info("Szpilplac kamraty.js "+VERSION);if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();
