-- Szpilplac: niezależna tabela odsłon i kliknięć analitycznych
-- Uruchom raz w Supabase SQL Editor po wcześniejszych skryptach analityki.
-- Skrypt jest idempotentny i nie usuwa wyników gier.

begin;

create table if not exists public.szpilplac_analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null,
  visitor_id text not null,
  value text not null,
  lang text not null default 'pl',
  constraint szpilplac_analytics_event_type_check
    check (event_type in ('page_view','support_click')),
  constraint szpilplac_analytics_visitor_length_check
    check (char_length(visitor_id) between 8 and 100),
  constraint szpilplac_analytics_value_length_check
    check (char_length(value) between 1 and 240),
  constraint szpilplac_analytics_lang_length_check
    check (char_length(lang) between 1 and 8)
);

alter table public.szpilplac_analytics_events enable row level security;

revoke all on table public.szpilplac_analytics_events from public;
revoke all on table public.szpilplac_analytics_events from anon;
revoke all on table public.szpilplac_analytics_events from authenticated;

create index if not exists szpilplac_analytics_events_type_created_idx
  on public.szpilplac_analytics_events (event_type, created_at desc);

create index if not exists szpilplac_analytics_events_type_visitor_idx
  on public.szpilplac_analytics_events (event_type, visitor_id);

create unique index if not exists szpilplac_analytics_events_migration_dedupe_idx
  on public.szpilplac_analytics_events (created_at, event_type, visitor_id, value);

-- Zachowaj ewentualne zdarzenia, które zdążyły zapisać się w starej tabeli.
insert into public.szpilplac_analytics_events (
  created_at,
  event_type,
  visitor_id,
  value,
  lang
)
select
  e.created_at,
  e.event_type,
  e.visitor_id,
  coalesce(nullif(e.puzzle_word,''),'/'),
  coalesce(nullif(e.lang,''),'pl')
from public.szpilplac_events e
where e.event_type in ('page_view','support_click')
  and nullif(e.visitor_id,'') is not null
on conflict do nothing;

create or replace function public.szpilplac_analytics_track(
  p_event_type text,
  p_visitor_id text,
  p_value text,
  p_lang text default 'pl'
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
set row_security = off
as $$
declare
  v_event_type text := lower(trim(coalesce(p_event_type,'')));
  v_visitor_id text := left(trim(coalesce(p_visitor_id,'')),100);
  v_value text := left(trim(coalesce(p_value,'')),240);
  v_lang text := left(trim(coalesce(p_lang,'pl')),8);
  v_window interval;
begin
  if v_event_type not in ('page_view','support_click') then
    return false;
  end if;

  if char_length(v_visitor_id) < 8 then
    return false;
  end if;

  if v_event_type = 'page_view' then
    if v_value = '' or left(v_value,1) <> '/' then
      return false;
    end if;
    v_window := interval '8 seconds';
  else
    if v_value = '' then
      v_value := 'link';
    end if;
    v_window := interval '2 seconds';
  end if;

  if exists (
    select 1
    from public.szpilplac_analytics_events e
    where e.event_type = v_event_type
      and e.visitor_id = v_visitor_id
      and e.value = v_value
      and e.created_at >= now() - v_window
  ) then
    return true;
  end if;

  insert into public.szpilplac_analytics_events (
    event_type,
    visitor_id,
    value,
    lang
  ) values (
    v_event_type,
    v_visitor_id,
    v_value,
    coalesce(nullif(v_lang,''),'pl')
  );

  return true;
end;
$$;

revoke all
  on function public.szpilplac_analytics_track(text,text,text,text)
  from public;

grant execute
  on function public.szpilplac_analytics_track(text,text,text,text)
  to anon;

grant execute
  on function public.szpilplac_analytics_track(text,text,text,text)
  to authenticated;

-- Widoki panelu są przebudowane tak, aby ruch pochodził z osobnej tabeli,
-- a ukończenia gier nadal z public.szpilplac_events.
drop view if exists public.stats_admin_analytics_health;
drop view if exists public.stats_admin_analytics_overview;
drop view if exists public.stats_admin_analytics_daily;
drop view if exists public.stats_admin_support_sources;
drop view if exists public.stats_admin_top_pages;
drop view if exists public.stats_admin_new_accounts;

create view public.stats_admin_analytics_overview
with (security_barrier = true)
as
with
admin_access as (
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(coalesce(p.rank_name,'')) = 'starzik'
  ) as allowed
),
calendar as (
  select timezone('Europe/Warsaw', now())::date as today
),
account_stats as (
  select
    count(*)::integer as accounts_total,
    count(*) filter (
      where timezone('Europe/Warsaw', u.created_at)::date = c.today
    )::integer as new_accounts_today,
    count(*) filter (
      where timezone('Europe/Warsaw', u.created_at)::date between c.today - 6 and c.today
    )::integer as new_accounts_7d,
    count(*) filter (
      where timezone('Europe/Warsaw', u.created_at)::date between c.today - 29 and c.today
    )::integer as new_accounts_30d
  from auth.users u
  cross join calendar c
),
analytics_stats as (
  select
    count(*) filter (
      where e.event_type = 'page_view'
        and timezone('Europe/Warsaw', e.created_at)::date = c.today
    )::integer as page_views_today,
    count(distinct e.visitor_id) filter (
      where e.event_type = 'page_view'
        and timezone('Europe/Warsaw', e.created_at)::date = c.today
    )::integer as visitors_today,
    count(*) filter (
      where e.event_type = 'page_view'
        and timezone('Europe/Warsaw', e.created_at)::date between c.today - 6 and c.today
    )::integer as page_views_7d,
    count(distinct e.visitor_id) filter (
      where e.event_type = 'page_view'
        and timezone('Europe/Warsaw', e.created_at)::date between c.today - 6 and c.today
    )::integer as visitors_7d,
    count(*) filter (
      where e.event_type = 'page_view'
        and timezone('Europe/Warsaw', e.created_at)::date between c.today - 29 and c.today
    )::integer as page_views_30d,
    count(distinct e.visitor_id) filter (
      where e.event_type = 'page_view'
        and timezone('Europe/Warsaw', e.created_at)::date between c.today - 29 and c.today
    )::integer as visitors_30d,
    count(*) filter (
      where e.event_type = 'support_click'
        and timezone('Europe/Warsaw', e.created_at)::date = c.today
    )::integer as support_clicks_today,
    count(*) filter (
      where e.event_type = 'support_click'
        and timezone('Europe/Warsaw', e.created_at)::date between c.today - 6 and c.today
    )::integer as support_clicks_7d,
    count(*) filter (
      where e.event_type = 'support_click'
        and timezone('Europe/Warsaw', e.created_at)::date between c.today - 29 and c.today
    )::integer as support_clicks_30d,
    max(e.created_at) filter (where e.event_type = 'page_view') as last_page_view
  from public.szpilplac_analytics_events e
  cross join calendar c
),
returning_stats as (
  select count(*)::integer as returning_visitors_7d
  from (
    select e.visitor_id
    from public.szpilplac_analytics_events e
    cross join calendar c
    where e.event_type = 'page_view'
      and timezone('Europe/Warsaw', e.created_at)::date between c.today - 6 and c.today
    group by e.visitor_id
    having count(distinct timezone('Europe/Warsaw', e.created_at)::date) >= 2
  ) q
),
game_stats as (
  select
    count(*) filter (
      where coalesce(nullif(e.event_type,''),'game_finish') = 'game_finish'
        and timezone('Europe/Warsaw', e.created_at)::date = c.today
    )::integer as game_finishes_today,
    count(distinct nullif(e.visitor_id,'')) filter (
      where coalesce(nullif(e.event_type,''),'game_finish') = 'game_finish'
        and timezone('Europe/Warsaw', e.created_at)::date = c.today
    )::integer as game_players_today,
    count(*) filter (
      where coalesce(nullif(e.event_type,''),'game_finish') = 'game_finish'
        and timezone('Europe/Warsaw', e.created_at)::date between c.today - 6 and c.today
    )::integer as game_finishes_7d,
    count(distinct nullif(e.visitor_id,'')) filter (
      where coalesce(nullif(e.event_type,''),'game_finish') = 'game_finish'
        and timezone('Europe/Warsaw', e.created_at)::date between c.today - 6 and c.today
    )::integer as game_players_7d,
    count(*) filter (
      where coalesce(nullif(e.event_type,''),'game_finish') = 'game_finish'
        and timezone('Europe/Warsaw', e.created_at)::date between c.today - 29 and c.today
    )::integer as game_finishes_30d,
    count(distinct nullif(e.visitor_id,'')) filter (
      where coalesce(nullif(e.event_type,''),'game_finish') = 'game_finish'
        and timezone('Europe/Warsaw', e.created_at)::date between c.today - 29 and c.today
    )::integer as game_players_30d
  from public.szpilplac_events e
  cross join calendar c
)
select
  a.accounts_total,
  a.new_accounts_today,
  a.new_accounts_7d,
  a.new_accounts_30d,
  s.page_views_today,
  s.visitors_today,
  s.page_views_7d,
  s.visitors_7d,
  s.page_views_30d,
  s.visitors_30d,
  g.game_finishes_today,
  g.game_players_today,
  g.game_finishes_7d,
  g.game_players_7d,
  g.game_finishes_30d,
  g.game_players_30d,
  s.support_clicks_today,
  s.support_clicks_7d,
  s.support_clicks_30d,
  r.returning_visitors_7d,
  s.last_page_view
from admin_access aa
cross join account_stats a
cross join analytics_stats s
cross join returning_stats r
cross join game_stats g
where aa.allowed;

create view public.stats_admin_analytics_daily
with (security_barrier = true)
as
with
admin_access as (
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(coalesce(p.rank_name,'')) = 'starzik'
  ) as allowed
),
days as (
  select generate_series(
    timezone('Europe/Warsaw', now())::date - 29,
    timezone('Europe/Warsaw', now())::date,
    interval '1 day'
  )::date as day
),
analytics_daily as (
  select
    timezone('Europe/Warsaw', e.created_at)::date as day,
    count(*) filter (where e.event_type = 'page_view')::integer as page_views,
    count(distinct e.visitor_id) filter (where e.event_type = 'page_view')::integer as visitors,
    count(*) filter (where e.event_type = 'support_click')::integer as support_clicks
  from public.szpilplac_analytics_events e
  where e.created_at >= now() - interval '31 days'
  group by 1
),
game_daily as (
  select
    timezone('Europe/Warsaw', e.created_at)::date as day,
    count(*) filter (
      where coalesce(nullif(e.event_type,''),'game_finish') = 'game_finish'
    )::integer as game_finishes,
    count(distinct nullif(e.visitor_id,'')) filter (
      where coalesce(nullif(e.event_type,''),'game_finish') = 'game_finish'
    )::integer as game_players
  from public.szpilplac_events e
  where e.created_at >= now() - interval '31 days'
  group by 1
),
account_daily as (
  select
    timezone('Europe/Warsaw', u.created_at)::date as day,
    count(*)::integer as new_accounts
  from auth.users u
  where u.created_at >= now() - interval '31 days'
  group by 1
)
select
  d.day,
  coalesce(ad.page_views,0)::integer as page_views,
  coalesce(ad.visitors,0)::integer as visitors,
  coalesce(gd.game_finishes,0)::integer as game_finishes,
  coalesce(gd.game_players,0)::integer as game_players,
  coalesce(ac.new_accounts,0)::integer as new_accounts,
  coalesce(ad.support_clicks,0)::integer as support_clicks
from days d
cross join admin_access aa
left join analytics_daily ad on ad.day = d.day
left join game_daily gd on gd.day = d.day
left join account_daily ac on ac.day = d.day
where aa.allowed
order by d.day desc;

create view public.stats_admin_support_sources
with (security_barrier = true)
as
with admin_access as (
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(coalesce(p.rank_name,'')) = 'starzik'
  ) as allowed
)
select
  e.value as source,
  count(*) filter (
    where timezone('Europe/Warsaw', e.created_at)::date = timezone('Europe/Warsaw', now())::date
  )::integer as clicks_today,
  count(*) filter (
    where timezone('Europe/Warsaw', e.created_at)::date >= timezone('Europe/Warsaw', now())::date - 6
  )::integer as clicks_7d,
  count(*) filter (
    where timezone('Europe/Warsaw', e.created_at)::date >= timezone('Europe/Warsaw', now())::date - 29
  )::integer as clicks_30d,
  count(*)::integer as clicks_total
from public.szpilplac_analytics_events e
cross join admin_access aa
where aa.allowed
  and e.event_type = 'support_click'
group by e.value
order by clicks_30d desc, clicks_total desc;

create view public.stats_admin_top_pages
with (security_barrier = true)
as
with admin_access as (
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(coalesce(p.rank_name,'')) = 'starzik'
  ) as allowed
)
select
  e.value as path,
  count(*) filter (
    where timezone('Europe/Warsaw', e.created_at)::date >= timezone('Europe/Warsaw', now())::date - 6
  )::integer as views_7d,
  count(distinct e.visitor_id) filter (
    where timezone('Europe/Warsaw', e.created_at)::date >= timezone('Europe/Warsaw', now())::date - 6
  )::integer as visitors_7d,
  count(*) filter (
    where timezone('Europe/Warsaw', e.created_at)::date >= timezone('Europe/Warsaw', now())::date - 29
  )::integer as views_30d,
  count(distinct e.visitor_id) filter (
    where timezone('Europe/Warsaw', e.created_at)::date >= timezone('Europe/Warsaw', now())::date - 29
  )::integer as visitors_30d
from public.szpilplac_analytics_events e
cross join admin_access aa
where aa.allowed
  and e.event_type = 'page_view'
group by e.value
order by views_30d desc, views_7d desc;

create view public.stats_admin_new_accounts
with (security_barrier = true)
as
with
admin_access as (
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(coalesce(p.rank_name,'')) = 'starzik'
  ) as allowed
),
results as (
  select
    user_id,
    count(*)::integer as games_played,
    max(coalesce(finished_at,created_at)) as last_play
  from public.user_game_results
  group by user_id
)
select
  u.id,
  p.login,
  u.created_at,
  p.city,
  p.voivodeship,
  coalesce(r.games_played,0)::integer as games_played,
  r.last_play
from auth.users u
cross join admin_access aa
left join public.profiles p on p.id = u.id
left join results r on r.user_id = u.id
where aa.allowed
order by u.created_at desc;

create view public.stats_admin_analytics_health
with (security_barrier = true)
as
with admin_access as (
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(coalesce(p.rank_name,'')) = 'starzik'
  ) as allowed
)
select
  count(*)::integer as events_total,
  count(*) filter (where event_type = 'page_view')::integer as page_views_total,
  count(*) filter (where event_type = 'support_click')::integer as support_clicks_total,
  max(created_at) as last_event,
  max(created_at) filter (where event_type = 'page_view') as last_page_view
from public.szpilplac_analytics_events
cross join admin_access aa
where aa.allowed;

revoke all on public.stats_admin_analytics_overview from anon;
revoke all on public.stats_admin_analytics_daily from anon;
revoke all on public.stats_admin_support_sources from anon;
revoke all on public.stats_admin_top_pages from anon;
revoke all on public.stats_admin_new_accounts from anon;
revoke all on public.stats_admin_analytics_health from anon;

grant select on public.stats_admin_analytics_overview to authenticated;
grant select on public.stats_admin_analytics_daily to authenticated;
grant select on public.stats_admin_support_sources to authenticated;
grant select on public.stats_admin_top_pages to authenticated;
grant select on public.stats_admin_new_accounts to authenticated;
grant select on public.stats_admin_analytics_health to authenticated;

notify pgrst, 'reload schema';

commit;

-- Test zapisu jako rola anon. Transakcja jest wycofywana, więc test nie zawyża statystyk.
begin;
set local role anon;
select public.szpilplac_analytics_track(
  'page_view',
  'diagnostic-v5-anon-client',
  '/__analytics_test__',
  'pl'
) as anon_rpc_write;
rollback;

-- Kontrola instalacji. Oczekiwane wartości:
-- analytics_table: szpilplac_analytics_events
-- analytics_rpc: szpilplac_analytics_track(text,text,text,text)
-- anon_can_execute: true
-- authenticated_can_execute: true
select
  to_regclass('public.szpilplac_analytics_events') as analytics_table,
  to_regprocedure('public.szpilplac_analytics_track(text,text,text,text)') as analytics_rpc,
  has_function_privilege(
    'anon',
    'public.szpilplac_analytics_track(text,text,text,text)',
    'EXECUTE'
  ) as anon_can_execute,
  has_function_privilege(
    'authenticated',
    'public.szpilplac_analytics_track(text,text,text,text)',
    'EXECUTE'
  ) as authenticated_can_execute;

select * from public.stats_admin_analytics_health;
select * from public.stats_admin_analytics_overview;
select * from public.stats_admin_analytics_daily limit 14;
